### ISSUE TITLE
Determining what to make for Breakfast

### ISSUE THREAD

**Issue by ccastilloux** [IntroToCode/Spring21_Recipes_Codemates15#1]
## 💬 Discussion topic

What should we make for breakfast?
Requirement: must have eggs

## 👥 People to consult

@Justinli90 @lancebarnardberkeley

## ❗ Potential issues

Converting the recipe for the wrong # of people (we should be cooking for 4 people)

## 📃 Details

Who's hungry??

**Comment by ccastilloux** [comment]
I think eggs and bacon would be a great breakfast - anyone not eat pork?

**Comment by lancebarnardberkeley** [comment]
Im not a vegetarian so looks good for me

**Comment by Justinli90** [comment]
@lancebarnardberkeley @ccastilloux @Aleixsc great job, thanks for the great teamwork on Breakfast! Closing Issue. 😁
