### ISSUE TITLE
Determining what to make for Lunch

### ISSUE THREAD

**Issue by Justinli90** [IntroToCode/Spring21_Recipes_Codemates15#2]
## 💬 Discussion topic

What should we make for lunch? 
Requirements/Criteria: Must be some sort of sandwich
## 👥 People to consult

@Justinli90 @lancebarnardberkeley @ccastilloux 

## ❗ Potential issues

Converting the recipe for the wrong # of people (we should be cooking for 4 people)

## 📃 Details

Who's hungry??

**Comment by Aleixsc** [comment]
I am starving!!

**Comment by Justinli90** [comment]
@lancebarnardberkeley @ccastilloux @Aleixsc great job, thanks for the great teamwork on Lunch! Closing Issue. 😁
